# Generated by Django 4.2.2 on 2023-06-24 03:49

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('R', 'Regular'), ('P', 'Premium')], default='R', max_length=1)),
                ('slot', models.ForeignKey(default=bookings.models.default_slot, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'slot'), name='unique_booking_for_user_per_slot'),
        ),
    ]
